language: node_js
node_js:
- 8
script:
- npm run test
notifications:
  email:
    on_failure: change
  slack:
    rooms:
    - confrer:yjflcetA76qbviTNMRWWA0IJ#eng
    on_success: change
    on_pull_requests: false
branches:
  only:
  - master
